name: automation
on: pull_request
jobs:
  ready-for-review:
    runs-on: ubuntu-latest
    steps:
    - name: pr to project card
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/EFDerbyshire/hl2rp-of-terror/projects/1
        GITHUB_PROJECT_COLUMN_NAME: "🔴 Code Review: Awaiting Review"
